version: 1
accounts:
- name: alice
  coins:
  - 200000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
  typescript:
    path: "ts-client"
  composables:
    path: "vue/src/composables"
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
genesis:
  app_state:
    staking:
      params:
        bond_denom: "stake"
    gov:
      params:
          voting_period: "600s"