// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateClass } from "./types/vcoa/vnft/tx";
import { MsgBurnNFT } from "./types/vcoa/vnft/tx";
import { MsgMintNft } from "./types/vcoa/vnft/tx";

import { ClassData as typeClassData} from "./types"
import { EventBurnNFT as typeEventBurnNFT} from "./types"
import { NftData as typeNftData} from "./types"
import { Params as typeParams} from "./types"
import { MsgBurnNFTResponse as typeMsgBurnNFTResponse} from "./types"

export { MsgCreateClass, MsgBurnNFT, MsgMintNft };

type sendMsgCreateClassParams = {
  value: MsgCreateClass,
  fee?: StdFee,
  memo?: string
};

type sendMsgBurnNFTParams = {
  value: MsgBurnNFT,
  fee?: StdFee,
  memo?: string
};

type sendMsgMintNftParams = {
  value: MsgMintNft,
  fee?: StdFee,
  memo?: string
};


type msgCreateClassParams = {
  value: MsgCreateClass,
};

type msgBurnNFTParams = {
  value: MsgBurnNFT,
};

type msgMintNftParams = {
  value: MsgMintNft,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateClass({ value, fee, memo }: sendMsgCreateClassParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateClass: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateClass({ value: MsgCreateClass.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateClass: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgBurnNFT({ value, fee, memo }: sendMsgBurnNFTParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBurnNFT: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgBurnNFT({ value: MsgBurnNFT.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBurnNFT: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgMintNft({ value, fee, memo }: sendMsgMintNftParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgMintNft: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgMintNft({ value: MsgMintNft.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgMintNft: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateClass({ value }: msgCreateClassParams): EncodeObject {
			try {
				return { typeUrl: "/vcoa.vnft.MsgCreateClass", value: MsgCreateClass.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateClass: Could not create message: ' + e.message)
			}
		},
		
		msgBurnNFT({ value }: msgBurnNFTParams): EncodeObject {
			try {
				return { typeUrl: "/vcoa.vnft.MsgBurnNFT", value: MsgBurnNFT.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBurnNFT: Could not create message: ' + e.message)
			}
		},
		
		msgMintNft({ value }: msgMintNftParams): EncodeObject {
			try {
				return { typeUrl: "/vcoa.vnft.MsgMintNft", value: MsgMintNft.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgMintNft: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						ClassData: getStructure(typeClassData.fromPartial({})),
						EventBurnNFT: getStructure(typeEventBurnNFT.fromPartial({})),
						NftData: getStructure(typeNftData.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						MsgBurnNFTResponse: getStructure(typeMsgBurnNFTResponse.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			VcoaVnft: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;